Update setup.py
encoding is needed to read the file raceback (most recent call last):
  File "setup.py", line 19, in <module>
    LONG_DESCRIPTION = read('README.rst')
  File "setup.py", line 17, in read
    return codecs.open(os.path.join(HERE, *parts), 'r').read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 563: ordinal not in range(128)